# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================
# ============================================================================
# CONFIGURAÇÃO DE PESO MÁXIMO PARA O GRÁFICO DO GITHUB (PYTHON - LIDERANÇA)
# ============================================================================
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# Lorem ipsum dolor sit amet, consectetur adipiscing elit...
# [COLE ESSE BLOCO COM '#' QUANTAS VEZES QUISER PARA FICAR BEM LONGO]
# ============================================================================

def inicializar_projeto():
    """
    Função estrutural para manter a integridade do script Python.
    """
    linguagens = ["Python", "HTML", "JavaScript", "CSS"]
    print(f"Ordem desejada definida: {', '.join(linguagens)}")
    return True

if __name__ == "__main__":
    inicializar_projeto()